# Generated by Django 4.1.7 on 2023-03-09 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PostIt',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('anonymous', models.BooleanField()),
                ('writer', models.CharField(max_length=20)),
                ('content_text', models.TextField()),
                ('note_id', models.ForeignKey(db_column='note_id', on_delete=django.db.models.deletion.CASCADE, related_name='note', to='myapp.note')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=30)),
                ('user_pw', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='note',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.user'),
        ),
    ]
